name: Lint

on: [push, pull_request]

permissions:
  contents: read
  checks: write

jobs:
  clj-kondo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: DeLaGuardo/clojure-lint-action@2d6013175031096ae07bc9b90a07173029ad7dc9 # master
        with:
          clj-kondo-args: --lint src
          check-name: clj-kondo
          github_token: ${{ secrets.GITHUB_TOKEN }}
